import type { Metadata } from "next";
import localFont from "next/font/local";
import Header from "../Components/header";
import Footer from "../Components/footer";
import "./globals.css";
import ReduxProvider from "../context/ReduxProvider";

const vazir = localFont({
  src: "../../public/font/vazir/Vazir-Medium.ttf",
  variable: "--font-vazirmatn",
});

export const metadata: Metadata = {
  title: "hoorsun app",
  description: "Generated by mohammad jalalabadi :)",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${vazir.className} relative`}>
        <Header />
        <ReduxProvider>{children}</ReduxProvider>
        <Footer />
      </body>
    </html>
  );
}
